 CREATE TABLE CLIENTS 
   (NCLIENT NUMBER PRIMARY KEY, 
	NOMCLIENT VARCHAR2(100 BYTE), 
	PRENOM VARCHAR2(100 BYTE), 
	ADRESSECLIENT VARCHAR2(100 BYTE), 
	VILLECLIENT VARCHAR2(100 BYTE), 
	AGE NUMBER(3,0)
   );
Insert into CLIENTS (NCLIENT,NOMCLIENT,PRENOM,ADRESSECLIENT,VILLECLIENT,AGE) values ('1','Hoover','Marshall','CP 540, 8343 Rhoncus Rd.','Casablanca','25');
Insert into CLIENTS (NCLIENT,NOMCLIENT,PRENOM,ADRESSECLIENT,VILLECLIENT,AGE) values ('2','Moody','Bert','199-1756 Purus Chemin','Rabat','21');
Insert into CLIENTS (NCLIENT,NOMCLIENT,PRENOM,ADRESSECLIENT,VILLECLIENT,AGE) values ('3','Cote','Gray','Appartement 720-3299 Id, Impasse','Rabat','86');
Insert into CLIENTS (NCLIENT,NOMCLIENT,PRENOM,ADRESSECLIENT,VILLECLIENT,AGE) values ('4','Williams','Echo','8672 Lorem Rd.','Casablanca','83');
Insert into CLIENTS (NCLIENT,NOMCLIENT,PRENOM,ADRESSECLIENT,VILLECLIENT,AGE) values ('5','Valentine','Adrian','1013 Lacus. Rd.','Rabat','90');
Insert into CLIENTS (NCLIENT,NOMCLIENT,PRENOM,ADRESSECLIENT,VILLECLIENT,AGE) values ('6','Barker','Cassidy','Appartement 325-3478 Felis. Impasse','Rabat','85');
Insert into CLIENTS (NCLIENT,NOMCLIENT,PRENOM,ADRESSECLIENT,VILLECLIENT,AGE) values ('7','England','Ursa','696-8889 Duis Rue','Rabat','60');
Insert into CLIENTS (NCLIENT,NOMCLIENT,PRENOM,ADRESSECLIENT,VILLECLIENT,AGE) values ('8','Johnson','Nayda','CP 165, 1503 Mauris, Ave','Rabat','6');
Insert into CLIENTS (NCLIENT,NOMCLIENT,PRENOM,ADRESSECLIENT,VILLECLIENT,AGE) values ('9','Tate','Brynne','Appartement 297-8163 Ante Ave','Rabat','18');
Insert into CLIENTS (NCLIENT,NOMCLIENT,PRENOM,ADRESSECLIENT,VILLECLIENT,AGE) values ('10','Kramer','Colton','8511 Vitae Rd.','Rabat','40');
Insert into CLIENTS (NCLIENT,NOMCLIENT,PRENOM,ADRESSECLIENT,VILLECLIENT,AGE) values ('11','Rios','Cameron','Appartement 929-5000 Luctus. Route','Casablanca','13');
Insert into CLIENTS (NCLIENT,NOMCLIENT,PRENOM,ADRESSECLIENT,VILLECLIENT,AGE) values ('12','Wall','Nathaniel','Appartement 175-9560 Sagittis Impasse','Casablanca','37');
Insert into CLIENTS (NCLIENT,NOMCLIENT,PRENOM,ADRESSECLIENT,VILLECLIENT,AGE) values ('13','Dodson','Carla','CP 155, 9134 Purus Av.','Rabat','97');
Insert into CLIENTS (NCLIENT,NOMCLIENT,PRENOM,ADRESSECLIENT,VILLECLIENT,AGE) values ('14','Wynn','Porter','CP 606, 2908 Curabitur Route','Casablanca','11');
Insert into CLIENTS (NCLIENT,NOMCLIENT,PRENOM,ADRESSECLIENT,VILLECLIENT,AGE) values ('15','Mercado','Quyn','CP 745, 6025 Nunc Rd.','Rabat','16');
Insert into CLIENTS (NCLIENT,NOMCLIENT,PRENOM,ADRESSECLIENT,VILLECLIENT,AGE) values ('16','Fletcher','Iris','8691 Ultrices. Avenue','Rabat','55');
Insert into CLIENTS (NCLIENT,NOMCLIENT,PRENOM,ADRESSECLIENT,VILLECLIENT,AGE) values ('17','Lynn','Michael','Appartement 114-8245 Morbi Rd.','Casablanca','52');
Insert into CLIENTS (NCLIENT,NOMCLIENT,PRENOM,ADRESSECLIENT,VILLECLIENT,AGE) values ('18','English','Nicole','Appartement 968-4866 Egestas Chemin','Casablanca','88');
Insert into CLIENTS (NCLIENT,NOMCLIENT,PRENOM,ADRESSECLIENT,VILLECLIENT,AGE) values ('19','Vaughn','Caesar','129-8119 Praesent Rd.','Rabat','81');
Insert into CLIENTS (NCLIENT,NOMCLIENT,PRENOM,ADRESSECLIENT,VILLECLIENT,AGE) values ('20','Palmer','Fulton','Appartement 427-1557 Quisque Avenue','Rabat','92');
Insert into CLIENTS (NCLIENT,NOMCLIENT,PRENOM,ADRESSECLIENT,VILLECLIENT,AGE) values ('21','Allen','Judah','Appartement 479-7418 Penatibus Avenue','Rabat','12');
Insert into CLIENTS (NCLIENT,NOMCLIENT,PRENOM,ADRESSECLIENT,VILLECLIENT,AGE) values ('22','Mccray','Axel','Appartement 723-9025 Natoque Rd.','Rabat','10');
Insert into CLIENTS (NCLIENT,NOMCLIENT,PRENOM,ADRESSECLIENT,VILLECLIENT,AGE) values ('23','Nieves','Hammett','Appartement 137-9770 Amet, Route','Rabat','12');
Insert into CLIENTS (NCLIENT,NOMCLIENT,PRENOM,ADRESSECLIENT,VILLECLIENT,AGE) values ('24','Crawford','Gwendolyn','CP 965, 5570 Imperdiet, Route','Rabat','73');
Insert into CLIENTS (NCLIENT,NOMCLIENT,PRENOM,ADRESSECLIENT,VILLECLIENT,AGE) values ('25','Horton','Hu','690-7400 Sodales Ave','Rabat','100');
Insert into CLIENTS (NCLIENT,NOMCLIENT,PRENOM,ADRESSECLIENT,VILLECLIENT,AGE) values ('26','Brown','Lara','CP 900, 2516 Eu Route','Casablanca','7');
Insert into CLIENTS (NCLIENT,NOMCLIENT,PRENOM,ADRESSECLIENT,VILLECLIENT,AGE) values ('27','Bird','Price','684-9792 Nibh Rd.','Rabat','48');
Insert into CLIENTS (NCLIENT,NOMCLIENT,PRENOM,ADRESSECLIENT,VILLECLIENT,AGE) values ('28','Price','Lev','3437 Cras Ave','Casablanca','64');
Insert into CLIENTS (NCLIENT,NOMCLIENT,PRENOM,ADRESSECLIENT,VILLECLIENT,AGE) values ('29','Salinas','Dana','Appartement 844-7114 Fermentum Ave','Rabat','74');
Insert into CLIENTS (NCLIENT,NOMCLIENT,PRENOM,ADRESSECLIENT,VILLECLIENT,AGE) values ('30','Key','Jemima','CP 856, 9663 Sapien Impasse','Casablanca','68');
Insert into CLIENTS (NCLIENT,NOMCLIENT,PRENOM,ADRESSECLIENT,VILLECLIENT,AGE) values ('31','Garrett','Abbot','8635 Scelerisque Avenue','Rabat','29');
Insert into CLIENTS (NCLIENT,NOMCLIENT,PRENOM,ADRESSECLIENT,VILLECLIENT,AGE) values ('32','Wilson','Hollee','453-8802 Auctor Rd.','Casablanca','18');
Insert into CLIENTS (NCLIENT,NOMCLIENT,PRENOM,ADRESSECLIENT,VILLECLIENT,AGE) values ('33','Torres','Deanna','CP 653, 2220 Risus. Av.','Rabat','56');
Insert into CLIENTS (NCLIENT,NOMCLIENT,PRENOM,ADRESSECLIENT,VILLECLIENT,AGE) values ('34','Lawrence','Reagan','530-3013 Lectus. Ave','Rabat','98');
Insert into CLIENTS (NCLIENT,NOMCLIENT,PRENOM,ADRESSECLIENT,VILLECLIENT,AGE) values ('35','Strickland','Kellie','CP 293, 4562 Libero Route','Casablanca','24');
Insert into CLIENTS (NCLIENT,NOMCLIENT,PRENOM,ADRESSECLIENT,VILLECLIENT,AGE) values ('36','Rodriquez','Shoshana','1910 Sed, Rd.','Rabat','89');
Insert into CLIENTS (NCLIENT,NOMCLIENT,PRENOM,ADRESSECLIENT,VILLECLIENT,AGE) values ('37','Whitley','Solomon','Appartement 234-5081 Augue. Rd.','Casablanca','10');
Insert into CLIENTS (NCLIENT,NOMCLIENT,PRENOM,ADRESSECLIENT,VILLECLIENT,AGE) values ('38','Barrett','Lara','CP 226, 6935 Sem Impasse','Rabat','14');
Insert into CLIENTS (NCLIENT,NOMCLIENT,PRENOM,ADRESSECLIENT,VILLECLIENT,AGE) values ('39','Hood','Natalie','Appartement 627-1898 Nunc. Impasse','Casablanca','41');
Insert into CLIENTS (NCLIENT,NOMCLIENT,PRENOM,ADRESSECLIENT,VILLECLIENT,AGE) values ('40','Klein','Cadman','Appartement 630-6369 Dolor Ave','Casablanca','39');
Insert into CLIENTS (NCLIENT,NOMCLIENT,PRENOM,ADRESSECLIENT,VILLECLIENT,AGE) values ('41','King','Warren','Appartement 136-2784 Fringilla Impasse','Rabat','52');
Insert into CLIENTS (NCLIENT,NOMCLIENT,PRENOM,ADRESSECLIENT,VILLECLIENT,AGE) values ('42','Nash','Donna','1417 Vitae, Ave','Rabat','68');
Insert into CLIENTS (NCLIENT,NOMCLIENT,PRENOM,ADRESSECLIENT,VILLECLIENT,AGE) values ('43','Humphrey','Neil','CP 972, 3193 Risus, Impasse','Rabat','60');
Insert into CLIENTS (NCLIENT,NOMCLIENT,PRENOM,ADRESSECLIENT,VILLECLIENT,AGE) values ('44','Compton','Morgan','CP 266, 6617 Tempor Ave','Rabat','87');
Insert into CLIENTS (NCLIENT,NOMCLIENT,PRENOM,ADRESSECLIENT,VILLECLIENT,AGE) values ('45','Cherry','Sage','162-2689 Magna Impasse','Casablanca','8');
Insert into CLIENTS (NCLIENT,NOMCLIENT,PRENOM,ADRESSECLIENT,VILLECLIENT,AGE) values ('46','Wooten','Montana','Appartement 914-846 Sed Chemin','Casablanca','37');
Insert into CLIENTS (NCLIENT,NOMCLIENT,PRENOM,ADRESSECLIENT,VILLECLIENT,AGE) values ('47','Downs','Barry','9849 Id Rd.','Casablanca','87');
Insert into CLIENTS (NCLIENT,NOMCLIENT,PRENOM,ADRESSECLIENT,VILLECLIENT,AGE) values ('48','Burnett','Armando','554-9297 Fermentum Impasse','Rabat','39');
Insert into CLIENTS (NCLIENT,NOMCLIENT,PRENOM,ADRESSECLIENT,VILLECLIENT,AGE) values ('49','Swanson','Imelda','CP 833, 7274 Consectetuer Route','Rabat','44');
Insert into CLIENTS (NCLIENT,NOMCLIENT,PRENOM,ADRESSECLIENT,VILLECLIENT,AGE) values ('50','Cook','Remedios','517-5391 Eu, Avenue','Rabat','64');
Insert into CLIENTS (NCLIENT,NOMCLIENT,PRENOM,ADRESSECLIENT,VILLECLIENT,AGE) values ('51','Hancock','Patrick','3840 Risus Avenue','Casablanca','100');
Insert into CLIENTS (NCLIENT,NOMCLIENT,PRENOM,ADRESSECLIENT,VILLECLIENT,AGE) values ('52','Shaffer','Kasimir','Appartement 945-7400 Semper Avenue','Casablanca','40');
Insert into CLIENTS (NCLIENT,NOMCLIENT,PRENOM,ADRESSECLIENT,VILLECLIENT,AGE) values ('53','Hicks','Summer','4219 Et Route','Casablanca','40');
Insert into CLIENTS (NCLIENT,NOMCLIENT,PRENOM,ADRESSECLIENT,VILLECLIENT,AGE) values ('54','Chan','Avram','Appartement 632-1434 Tristique Avenue','Casablanca','50');
Insert into CLIENTS (NCLIENT,NOMCLIENT,PRENOM,ADRESSECLIENT,VILLECLIENT,AGE) values ('55','Craig','Orlando','376-5952 Eleifend, Route','Rabat','8');
Insert into CLIENTS (NCLIENT,NOMCLIENT,PRENOM,ADRESSECLIENT,VILLECLIENT,AGE) values ('56','Blanchard','Carly','222-6891 Nec Ave','Casablanca','5');
Insert into CLIENTS (NCLIENT,NOMCLIENT,PRENOM,ADRESSECLIENT,VILLECLIENT,AGE) values ('57','Frank','Wilma','Appartement 114-1945 Elit, Rue','Casablanca','18');
Insert into CLIENTS (NCLIENT,NOMCLIENT,PRENOM,ADRESSECLIENT,VILLECLIENT,AGE) values ('58','Rivera','Lynn','1386 Cursus, Chemin','Casablanca','22');
Insert into CLIENTS (NCLIENT,NOMCLIENT,PRENOM,ADRESSECLIENT,VILLECLIENT,AGE) values ('59','Graves','Emily','335-6092 Eu, Rd.','Rabat','55');
Insert into CLIENTS (NCLIENT,NOMCLIENT,PRENOM,ADRESSECLIENT,VILLECLIENT,AGE) values ('60','Mercer','Cade','CP 673, 677 Et, Impasse','Casablanca','36');
Insert into CLIENTS (NCLIENT,NOMCLIENT,PRENOM,ADRESSECLIENT,VILLECLIENT,AGE) values ('61','Erickson','Harper','CP 831, 1118 Aliquam Rue','Casablanca','17');
Insert into CLIENTS (NCLIENT,NOMCLIENT,PRENOM,ADRESSECLIENT,VILLECLIENT,AGE) values ('62','Horton','Raya','573-1494 Aliquam Rue','Casablanca','27');
Insert into CLIENTS (NCLIENT,NOMCLIENT,PRENOM,ADRESSECLIENT,VILLECLIENT,AGE) values ('63','Mann','Zeus','4048 Consectetuer Route','Casablanca','41');
Insert into CLIENTS (NCLIENT,NOMCLIENT,PRENOM,ADRESSECLIENT,VILLECLIENT,AGE) values ('64','Marquez','Zachery','483-6141 Eu Ave','Casablanca','74');
Insert into CLIENTS (NCLIENT,NOMCLIENT,PRENOM,ADRESSECLIENT,VILLECLIENT,AGE) values ('65','Nicholson','Samson','Appartement 711-2036 Nec Rue','Rabat','43');
Insert into CLIENTS (NCLIENT,NOMCLIENT,PRENOM,ADRESSECLIENT,VILLECLIENT,AGE) values ('66','Nielsen','Samuel','CP 472, 8735 A, Impasse','Rabat','84');
Insert into CLIENTS (NCLIENT,NOMCLIENT,PRENOM,ADRESSECLIENT,VILLECLIENT,AGE) values ('67','Andrews','Dennis','1434 Massa Ave','Rabat','99');
Insert into CLIENTS (NCLIENT,NOMCLIENT,PRENOM,ADRESSECLIENT,VILLECLIENT,AGE) values ('68','Ramirez','Courtney','9187 Tortor. Rue','Casablanca','80');
Insert into CLIENTS (NCLIENT,NOMCLIENT,PRENOM,ADRESSECLIENT,VILLECLIENT,AGE) values ('69','Welch','Thor','774-5531 Dictum Rd.','Casablanca','73');
Insert into CLIENTS (NCLIENT,NOMCLIENT,PRENOM,ADRESSECLIENT,VILLECLIENT,AGE) values ('70','Roman','Gail','CP 804, 2010 Vulputate Ave','Casablanca','50');
Insert into CLIENTS (NCLIENT,NOMCLIENT,PRENOM,ADRESSECLIENT,VILLECLIENT,AGE) values ('71','Fuentes','Tatyana','2960 Mauris Ave','Casablanca','57');
Insert into CLIENTS (NCLIENT,NOMCLIENT,PRENOM,ADRESSECLIENT,VILLECLIENT,AGE) values ('72','Pratt','Dacey','3583 Sed, Av.','Rabat','2');
Insert into CLIENTS (NCLIENT,NOMCLIENT,PRENOM,ADRESSECLIENT,VILLECLIENT,AGE) values ('73','Ayers','Addison','6005 Egestas Ave','Casablanca','13');
Insert into CLIENTS (NCLIENT,NOMCLIENT,PRENOM,ADRESSECLIENT,VILLECLIENT,AGE) values ('74','Dawson','Tashya','CP 417, 4773 Ac, Route','Rabat','89');
Insert into CLIENTS (NCLIENT,NOMCLIENT,PRENOM,ADRESSECLIENT,VILLECLIENT,AGE) values ('75','Glass','Lunea','897-2761 Mi Av.','Casablanca','20');
Insert into CLIENTS (NCLIENT,NOMCLIENT,PRENOM,ADRESSECLIENT,VILLECLIENT,AGE) values ('76','Everett','Dacey','Appartement 774-8491 Donec Av.','Rabat','17');
Insert into CLIENTS (NCLIENT,NOMCLIENT,PRENOM,ADRESSECLIENT,VILLECLIENT,AGE) values ('77','Gallegos','Seth','Appartement 663-4581 Vulputate, Chemin','Rabat','6');
Insert into CLIENTS (NCLIENT,NOMCLIENT,PRENOM,ADRESSECLIENT,VILLECLIENT,AGE) values ('78','Holden','Xandra','Appartement 644-2443 Magna. Av.','Rabat','84');
Insert into CLIENTS (NCLIENT,NOMCLIENT,PRENOM,ADRESSECLIENT,VILLECLIENT,AGE) values ('79','Bates','Susan','CP 292, 2876 Nisl. Av.','Casablanca','69');
Insert into CLIENTS (NCLIENT,NOMCLIENT,PRENOM,ADRESSECLIENT,VILLECLIENT,AGE) values ('80','James','Helen','Appartement 317-7450 Nunc. Impasse','Rabat','22');
Insert into CLIENTS (NCLIENT,NOMCLIENT,PRENOM,ADRESSECLIENT,VILLECLIENT,AGE) values ('81','Bradshaw','Griffin','CP 330, 3551 Turpis Rue','Rabat','33');
Insert into CLIENTS (NCLIENT,NOMCLIENT,PRENOM,ADRESSECLIENT,VILLECLIENT,AGE) values ('82','Foster','Azalia','Appartement 715-9299 Erat. Avenue','Rabat','58');
Insert into CLIENTS (NCLIENT,NOMCLIENT,PRENOM,ADRESSECLIENT,VILLECLIENT,AGE) values ('83','Daniels','Kelsey','Appartement 587-2748 Purus Rue','Rabat','6');
Insert into CLIENTS (NCLIENT,NOMCLIENT,PRENOM,ADRESSECLIENT,VILLECLIENT,AGE) values ('84','Fuller','Stephen','164-9831 Rutrum. Av.','Casablanca','11');
Insert into CLIENTS (NCLIENT,NOMCLIENT,PRENOM,ADRESSECLIENT,VILLECLIENT,AGE) values ('85','Harrell','Doris','CP 280, 8954 Feugiat Route','Rabat','99');
Insert into CLIENTS (NCLIENT,NOMCLIENT,PRENOM,ADRESSECLIENT,VILLECLIENT,AGE) values ('86','Wallace','Bianca','4464 Et Impasse','Casablanca','81');
Insert into CLIENTS (NCLIENT,NOMCLIENT,PRENOM,ADRESSECLIENT,VILLECLIENT,AGE) values ('87','Dyer','Desirae','4146 Sit Chemin','Casablanca','100');
Insert into CLIENTS (NCLIENT,NOMCLIENT,PRENOM,ADRESSECLIENT,VILLECLIENT,AGE) values ('88','Vinson','Victor','CP 911, 4204 Tempus, Ave','Casablanca','55');
Insert into CLIENTS (NCLIENT,NOMCLIENT,PRENOM,ADRESSECLIENT,VILLECLIENT,AGE) values ('89','Sosa','Amber','208-502 Vehicula Avenue','Rabat','67');
Insert into CLIENTS (NCLIENT,NOMCLIENT,PRENOM,ADRESSECLIENT,VILLECLIENT,AGE) values ('90','Stevens','Zelenia','194 Aliquet Route','Rabat','99');
Insert into CLIENTS (NCLIENT,NOMCLIENT,PRENOM,ADRESSECLIENT,VILLECLIENT,AGE) values ('91','Maldonado','Quynn','Appartement 699-994 Fermentum Impasse','Casablanca','42');
Insert into CLIENTS (NCLIENT,NOMCLIENT,PRENOM,ADRESSECLIENT,VILLECLIENT,AGE) values ('92','Brock','Rinah','Appartement 268-4407 Mauris Impasse','Casablanca','43');
Insert into CLIENTS (NCLIENT,NOMCLIENT,PRENOM,ADRESSECLIENT,VILLECLIENT,AGE) values ('93','Franco','Kareem','9410 Non, Rue','Casablanca','8');
Insert into CLIENTS (NCLIENT,NOMCLIENT,PRENOM,ADRESSECLIENT,VILLECLIENT,AGE) values ('94','Wolfe','Kenneth','2508 Facilisis Rd.','Casablanca','17');
Insert into CLIENTS (NCLIENT,NOMCLIENT,PRENOM,ADRESSECLIENT,VILLECLIENT,AGE) values ('95','Burgess','Yoshi','3553 Nunc Av.','Casablanca','36');
Insert into CLIENTS (NCLIENT,NOMCLIENT,PRENOM,ADRESSECLIENT,VILLECLIENT,AGE) values ('96','Huber','Josephine','715 Convallis, Rd.','Casablanca','73');
Insert into CLIENTS (NCLIENT,NOMCLIENT,PRENOM,ADRESSECLIENT,VILLECLIENT,AGE) values ('97','Fleming','Rahim','CP 885, 4014 Laoreet Rue','Casablanca','33');
Insert into CLIENTS (NCLIENT,NOMCLIENT,PRENOM,ADRESSECLIENT,VILLECLIENT,AGE) values ('98','Britt','Abra','8667 Laoreet Av.','Casablanca','57');
Insert into CLIENTS (NCLIENT,NOMCLIENT,PRENOM,ADRESSECLIENT,VILLECLIENT,AGE) values ('99','Dillon','Jaime','6080 Non, Chemin','Casablanca','64');
Insert into CLIENTS (NCLIENT,NOMCLIENT,PRENOM,ADRESSECLIENT,VILLECLIENT,AGE) values ('100','Giles','Anjolie','326-7401 Lobortis. Ave','Rabat','35');
Insert into CLIENTS (NCLIENT,NOMCLIENT,PRENOM,ADRESSECLIENT,VILLECLIENT,AGE) values ('101','Dominique','Charle','125 Racine','Casablanca','45');